name: neom_home
description: Home for Open Neom.
version: 2.0.0
homepage: https://github.com/Open-Neom/neom_home

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  neom_core: ^3.0.0
  neom_commons: ^3.0.0

  # TRANSITIVE DEPENDENCIES FOR PUB.DEV PUBLISHING
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
